# Do not forget to create the .env file (see template)
# before using this container!

version: '2'

services:
    www:
        restart: always
        build: .
        environment:
            PORT: 8080
        ports:
            - $PORT:80
